### ISSUE TITLE
Install RealDebridManager without root

### ISSUE THREAD

**Issue by phiivas** [hyperbunny77/RealDebridManager#9]
Is there any way to install RealDebridManager without root. I am subscribed to ultra.cc seedbox, but I do not have root access there and accordingly installation of docker containers is impossible?

**Comment by hyperbunny77** [comment]
Hi, 

Apologies if i misunderstand. 

Are you saying you can install docker containers but not run them as root or simply not run them at all?

If you cannot run docker containers what can you run? Would for example you be able to run bash script?

I am thinking if this is possible I could explain how to run the needed python script yourself without docker.

**Comment by phiivas** [comment]
Hi,

I apologize for not being clear enough. 

Ultra.cc has a panel through which you can install and uninstall the officially supported applications with one click of the mouse, which I guess are in docker containers, but this panel is missing some of the apps i want to have.

<img width="1324" alt="Screenshot1" src="https://user-images.githubusercontent.com/38891301/174606343-c36e7c39-477b-4d71-93c0-0961ee4598f5.png">

There is also SSH access without root, therefore, docker containers installations are not possible, nor can they be started:

<img width="568" alt="Screenshot2" src="https://user-images.githubusercontent.com/38891301/174607449-258433b3-0e69-4dfc-9bb0-1623c4f7c5ab.png">

However, with apps that allows python installations everything works great. For example, piejanssens/premiumizer was installed and started successfully with this script:

$ git clone https://github.com/piejanssens/premiumizer.git premiumizer
$ cd premiumizer
$ pip install -r requirements.txt
$ python premiumizer/premiumizer.py

The Python version on the server is:
Python 3.8.13

Thanks

**Comment by phiivas** [comment]
Hi,

I tried different combinations to install your app via python, but without success!
I tried to mimic the the piejanssens script and the result is this:

`user@server:~/.apps$ git clone https://github.com/hyperbunny77/RealDebridManager.git RealDebridManager`

```
Cloning into 'RealDebridManager'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 105 (delta 61), reused 49 (delta 22), pack-reused 0
Receiving objects: 100% (105/105), 26.41 KiB | 2.40 MiB/s, done.
Resolving deltas: 100% (61/61), done.
```

`user@server:~/.apps$ cd RealDebridManager`

`user@server:~/.apps/RealDebridManager$ pip install -r requirements.txt`

```
Requirement already satisfied: appdirs==1.4.4 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: aria2p==0.11.2 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.11.2)
Requirement already satisfied: bencodepy==0.9.5 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.9.5)
Requirement already satisfied: certifi==2022.6.15 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (2022.6.15)
Requirement already satisfied: charset-normalizer==2.0.12 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (2.0.12)
Requirement already satisfied: click==8.1.3 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (8.1.3)
Requirement already satisfied: ConfigArgParse==1.5.3 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (1.5.3)
Requirement already satisfied: Flask==2.1.2 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (2.1.2)
Requirement already satisfied: Flask-BasicAuth==0.2.0 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (0.2.0)
Requirement already satisfied: gunicorn==20.1.0 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (20.1.0)
Requirement already satisfied: idna==3.3 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (3.3)
Requirement already satisfied: importlib-metadata==4.11.4 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (4.11.4)
Requirement already satisfied: itsdangerous==2.1.2 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (2.1.2)
Requirement already satisfied: Jinja2==3.1.2 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (3.1.2)
Requirement already satisfied: loguru==0.6.0 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (0.6.0)
Requirement already satisfied: MarkupSafe==2.1.1 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (2.1.1)
Requirement already satisfied: pyben==0.3.2 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (0.3.2)
Requirement already satisfied: pyinotify==0.9.6 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (0.9.6)
Requirement already satisfied: requests==2.28.0 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (2.28.0)
Requirement already satisfied: toml==0.10.2 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (0.10.2)
Requirement already satisfied: torrentfile==0.7.11 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (0.7.11)
Requirement already satisfied: urllib3==1.26.9 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 22)) (1.26.9)
Requirement already satisfied: websocket-client==1.3.2 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 23)) (1.3.2)
Requirement already satisfied: Werkzeug==2.1.2 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 24)) (2.1.2)
Requirement already satisfied: xdg==5.1.1 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 25)) (5.1.1)
Requirement already satisfied: zipp==3.8.0 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from -r requirements.txt (line 26)) (3.8.0)
Requirement already satisfied: setuptools>=3.0 in /home24/phivas/.pyenv/versions/3.8.13/lib/python3.8/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 10)) (62.4.0)
```

I don't know which file to choose, so I chose a random one:

`user@server:~/.apps/RealDebridManager$ python mainwebui.py`

```
* Serving Flask app 'mainwebui' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: xxx-xxx-xxx
```
 
Can you please provide the needed python script here and also explain how to change the port and the ip?

Thanks

**Comment by hyperbunny77** [comment]
Hi There,

So I am working on a new version of this project which has a lot more documentation!

In your case there needs to be 2 scripts to run, 

mainwebui.py - This runs the web interface and is standalone to access the dashboard 
FileWatch.py - This runs the "watcher" which watches the folder for files. Once it detects one it fires off another instance of python under either "rdtorrent" or "rdmagnet" these don't need to be run as this script will be in charge here.

Alternatively if you can run a bash file you could run the startscript.sh. You make need to make small changes to run both concurrently (unsure if your use case)

Either way, Let me know how you get on. You should be able to run this easily without root/docker.

**Comment by hyperbunny77** [comment]
Apologies missed your second part, 

To change the IP you could set Environment variables in your terminal. 

If you use Guinicorn to server the Webui : 

`exec gunicorn --bind 0.0.0.0:$rdmport mainwebui:app`

You can set environment variable of "rdmport" and webui will run there. 

If this doesn't work let me know and I could write a bash script for your setup.

**Comment by phiivas** [comment]
Hi,

So when I execute:

`user@server:~/.apps/RealDebridManager$/bash startscript.sh
`

I get this:

```
Traceback (most recent call last):
  File "FileWatch.py", line 12, in <module>
    connection = sqlite3.connect(databaseinfo, timeout=20)
sqlite3.OperationalError: unable to open database file
[2022-06-26 17:37:22 +0200] [67179] [INFO] Starting gunicorn 20.1.0
[2022-06-26 17:37:22 +0200] [67179] [INFO] Listening at: http://**.***.***.***:13808 (67179)
[2022-06-26 17:37:22 +0200] [67179] [INFO] Using worker: sync
[2022-06-26 17:37:22 +0200] [67269] [INFO] Booting worker with pid: 67269
```
Regarding the sqlite3 error in FileWatch.py I started this script: [sqlite-installer.sh](https://github.com/ultraseedbox/UltraSeedbox-Scripts/blob/master/Language%20Installers/sqlite-installer.sh) and installed sqlite3, but the error remains.

The startscript.sh looks now like that:

```
#!/bin/bash
exec python3 FileWatch.py &
exec gunicorn --bind **.***.***.***:13808 mainwebui:app
```

nothing is changed in the result by adding mainwebui.py after & !

Because the shell window is inaccessible once I run bash startscript.sh, I have to run a second shell window and to execute python mainwebui.py, but unfortunately the ip and the port are still the same:

```
* Serving Flask app 'mainwebui' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
 * Restarting with watchdog (inotify)
 * Debugger is active!
 * Debugger PIN: ***-***-***
```


It would be great if you provide a working startscript.sh, which starts the both .py and change the ip and the port, also to tell me, how to deal with the sqlite3 error.

Thanks

**Comment by hyperbunny77** [comment]
Hi There,

Thanks for your quick response!

Please can you firstly re clone the repo to get the changed files. 

Now can you open the new script i have created for your use case ("Non-Docker.sh")

`sudo nano Non-Docker.sh`

Next please change the directories and ports as needed.

**dbinfo** = Where the Database file will be stored. 
**watchpath**=Path to watch for torrents. (Where your radarr/sonarr has torrent black hole pointed to)
**Port 8003** - Random port I chose, Replace this with your preferred port for the webui to run its interface on.

Now when you run `Non-Docker.sh` in your terminal you should be able to access the application at the port chosen!

Let me know if this works?

**Comment by hyperbunny77** [comment]
The issues you are having with SQLite are not issues, These instead stem from confusion on your end. 

SQLite runs totally within a file and does not need any install, I am unsure what you have installed. 

Simply edit the script in my previous reply to a suitable location (database will never be more then 5MB or so) 

The program will generate the database and sort all of this.

**Comment by hyperbunny77** [comment]
Also...

You need a running instance of aria2 which will actually download the files here. 

You may have this already working and if so great!

If not its a quick install : `sudo apt-get install aria2` - Assuming your running Ubuntu/Debian based.

To run aria2 in background mode you can use : `aria2c --enable-rpc --rpc-listen-all --rpc-secret="mysecret" --dir=/mydownloadsdir`

To be more complex if you search online for aria2 config, You can start the software with a lot of options!

Once you have this running insert the details in settings of Real Debrid Manager.

If running on the same box use Hostname as `http://localhost`.

**Comment by phiivas** [comment]
Hi, 
Thank you very much, the last update was a big step forward!
I managed to start Aria2 and RealDebridManager and I have already downloaded several movies.

<img width="1429" alt="Screenshot 2022-06-28 at 13 57 43" src="https://user-images.githubusercontent.com/38891301/176176563-f5984bf7-345a-4409-a43f-2e6fa6a9d9b2.png">

<img width="716" alt="Screenshot 2022-06-28 at 14 00 43" src="https://user-images.githubusercontent.com/38891301/176176651-277f4d9a-91c9-4346-aef7-a93fddd15bac.png">

<img width="1198" alt="Screenshot 2022-06-28 at 13 59 54" src="https://user-images.githubusercontent.com/38891301/176176754-7b233dac-75ef-4ca6-8309-7c1f3316bbf4.png">

Non-Docker.sh

```
#!/bin/bash
export dbinfo=/home/phivas/.config/realdebridmanager/main.db # Change to where your DB should be stored
export watchpath=/home/phivas/downloads/blackhole/watch # Change to your watch path where torrents are placed
exec python3 FileWatch.py & # Runs background watch service
exec gunicorn --bind **.***.***.***:13820 mainwebui:app #Runs Web UI, Change Port as needed
```


But it is still far from perfect!


I can't execute the `sudo` command:

```
phivas@server:~/.apps/RealDebridManager$ sudo nano Non-Docker.sh
[sudo] password for phivas: 
Sorry, user phivas is not allowed to execute '/bin/nano Non-Docker.sh' as root on ******.*****.**.
phivas@altair:~/.apps/RealDebridManager$ 
```
Fortunately, Aria2 is installed by default on the server and I don't have to install it through `sudo`


When I start Aria2, it looks like that:

`aria2c --enable-rpc --rpc-listen-all --rpc-secret=*********** --dir=/home/phivas/downloads/blackhole/downloads`

This error comes out:

<img width="882" alt="Screenshot 2022-06-28 at 14 05 43" src="https://user-images.githubusercontent.com/38891301/176179514-21bfd9df-c3aa-4df2-b2d9-e1b4e5ff0ee6.png">


So I added: `--disable-ipv6` and the error disappeared.

The main problem now is that RealDebridManager and Aria2 works until I terminate the shell. I can still access the web interface on RDM, but I guess FileWatch.py and aria2c stops working.

I tried to keep Aria2 alive with -D and it survives after shell termination, but RDM gives some errors when I try to download something:

`aria2c --enable-rpc --rpc-listen-all --disable-ipv6 --rpc-secret=******** --dir=/home/phivas/downloads/blackhole/downloads -D`

I also tried home/phivas/.config/systemd/user/

aria2.service

```
[Unit]
Description=Aria2c download manager
After=network.target
[Service]
Type=simple
User=www-data
ExecStart=usr/bin/aria2c --enable-rpc --rpc-listen-all --rpc-secret=*********** --conf-path=/home/phivas/.config/aria2.daemon
[Install]
WantedBy=multi-user.target
```

aria2.daemon

```
continue
dir=/home/phivas/downloads/blackhole/downloads
file-allocation=trunc
max-connection-per-server=4
max-concurrent-downloads=2
max-overall-download-limit=0
min-split-size=25M
```

but without success!

It would be great if there is a way to start Aria2 and RDM as services!

**Comment by hyperbunny77** [comment]
Hi,

Glad some progress is being made! 

I need to look into how to run it as a service. Maybe this is adding the Script as a Cron job?

In the meantime, When you leave Aria2 running in background (mentioned in your post) you said there was an error in RDM. Could you share the logs? Maybe you will need to run in a separate SSH session to catch the logs?

I should add I am rebuilding the application from the ground up. I am taking into account the entire "Non Docker" approach and should have better support in the near future.

**Comment by hyperbunny77** [comment]
Also! On the above I said to use `sudo nano Non-Docker.sh`

No sudo is needed here. This is a bad habit of mine!

Simply editing the file doesn't require privilege.

**Comment by phiivas** [comment]
Hi, I apologize for not responding to your post for so long, but I was traveling and didn't have stable internet for testing.

So, when I leave Aria2 running in background I get errors like this:

```
File "RDmagnet.py", line 188, in <module>
    realdebridtorrent(magnetlink)
  File "RDmagnet.py", line 156, in realdebridtorrent
    moveprocessed(magnet, error)
```
still it works well and I can download without problems!
Please see the entire log in the attached file!

<img width="1359" alt="Screenshot 2022-07-14 at 17 51 39" src="https://user-images.githubusercontent.com/38891301/179011819-5ab1a928-40b3-4138-82cc-1eecdcc2c80b.png">

I was also able to keep processes alive after terminating ssh with the command `nohub`:

`nohup bash Non-Docker.sh`

But now I have a new issue, most torrents come archived in rar and Sonarr&Radarr cannot deal with archives. I installed unpackerr, but i can't get it to work at all. It sees the files but doesn't unrar them. 

Is there any way to set Aria2 to once it finishes downloading a file then to unrar it?

And my second question: Is there a way for RDM to only receive cached torrents?

Or maybe you can recommend me some trackers to add to prowlarr, that don't send archived content and usually real debrid has them already cached.

[log.txt](https://github.com/hyperbunny77/RealDebridManager/files/9113057/log.txt)


Thanks!
